// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpUCXTB5ycQTxO8ArrWT8kovTtFEJjVBI',
    appId: '1:745319101417:web:87d3b3dec228bcb8741178',
    messagingSenderId: '745319101417',
    projectId: 'task-manager-rjinfor',
    authDomain: 'task-manager-rjinfor.firebaseapp.com',
    storageBucket: 'task-manager-rjinfor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZoPskonwI12C0nAklTmecwlutmfrt38E',
    appId: '1:745319101417:android:75444e776558257b741178',
    messagingSenderId: '745319101417',
    projectId: 'task-manager-rjinfor',
    storageBucket: 'task-manager-rjinfor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXDStnSsqChKNCLUCMbtybZfJstnrUS4E',
    appId: '1:745319101417:ios:5236d8b37bb80b35741178',
    messagingSenderId: '745319101417',
    projectId: 'task-manager-rjinfor',
    storageBucket: 'task-manager-rjinfor.appspot.com',
    iosClientId: '745319101417-2ldf1denuk7m0iv4qv01innchvmpli44.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksmgr',
  );
}
